### ISSUE TITLE
Upgrade to RingCentral JS SDK 2.x

### ISSUE THREAD

**Issue by grokify** [ringcentral/ringcentral-cti-demo-js#3]
Upgrade the demo app's RingCentral JS SDK from version 1.x to 2.x.

**Comment by chenghaoc** [comment]
@grokify 
Currently all dependencies are build-in in the repo. Does it need to use Bower to manage the vendor packages? It will make the migration easier.

Ideally, use cdn for JS SDK is the best option I think.

**Comment by grokify** [comment]
The original requirements were that the static files needed to be copied directly to a static HTML pages server without dependencies so Bower was excluded.

One option is to introduce Bower and have running Bower be a requirement before a GitHub pages or other static page deployment.

Regarding CDN, we are looking to add the JS SDK to a CDN:
- https://github.com/ringcentral/ringcentral-js/issues/7

Until then, the JS SDK is available on GitHub in the "build" folder:
- Master: https://github.com/ringcentral/ringcentral-js/tree/master/build
- JS SDK 2.0.4: https://github.com/ringcentral/ringcentral-js/tree/a4625cbb9bf35cc892f82f917d8407874eba861f/build

A number of dependencies are also available on [cdnjs](https://cdnjs.com/) already.

**Comment by grokify** [comment]
@changbenny The new version being worked on now for JS SDK 2.0 uses Bower for `ringcentral` and `ringcentral-helpers` and more CDNs where applicable.

**Comment by grokify** [comment]
Completed in commit `b020624` for applicable dependencies:
- `es6-promise`
- `fetch`
- `pubnub`

Some outstanding libs include the following added via Bower:
- `ringcentral`
- `ringcentral-helpers`

And some remaining local libs.
